name: multibench
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2021.10.8=py39h06a4308_2
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_0
  - libstdcxx-ng=11.2.0=h1234567_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - openssl=1.1.1o=h7f8727e_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.6=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - scipy=1.7.1=py39h292c36d_2
  - setuptools=61.2.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_1
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - aiosignal==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distlib==0.3.4
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.7.1
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - future==0.18.2
    - grpcio==1.43.0
    - h5py==3.6.0
    - hyperopt==0.2.7
    - idna==3.3
    - ipykernel==6.14.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.0
    - jupyter-client==7.3.4
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - memory-profiler==0.60.0
    - mistune==0.8.4
    - msgpack==1.0.4
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.3
    - notebook==6.4.12
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - platformdirs==2.5.2
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.5
    - pycparser==2.21
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.1.0
    - ray==1.12.1
    - requests==2.27.1
    - scikit-learn==1.1.0
    - send2trash==1.8.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tabulate==0.8.9
    - tensorboardx==2.5.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - torch==1.11.0
    - torchtext==0.12.0
    - torchvision==0.12.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.2.2.post1
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
